analyzer = CommitAnalyzer("megaladonntm-arch", "ShadowSkills", "d0e7d528d11e5270da48ad837031a69381049b34")
report = analyzer.get_detailed_report()
print(report)
summary_dict = analyzer.get_commit_summary_dict()
print(summary_dict)
time_difference_days = analyzer.get_time_between_commits_days()
print(f"Time between commits: {time_difference_days} days")
is_merge = analyzer.is_merge_commit()
print(f"Is merge commit: {is_merge}")
changed_files = analyzer.get_changed_files()
print(f"Changed files: {changed_files}")
commit_tags = analyzer.get_commit_tags()
print(f"Commit tags: {commit_tags}")
commit_branch = analyzer.get_commit_branch()
print(f"Commit branch: {commit_branch}")
skill_analyzer = SkillMarketValueAnalyzer("megaladonntm-arch", "ShadowSkills", "d0e7d528d11e5270da48ad837031a69381049b34")
skill_market_value = skill_analyzer.analyze_skill_market_value()
print(f"Skill Market Value: {skill_market_value}")
summary = analyzer.given_summary()
print(summary)
grade = analyzer.grade_commit()
print(grade)
