#analyzer = CommitAnalyzer("megaladonntm-arch", "ShadowSkills", "d0e7d528d11e5270da48ad837031a69381049b34")
#report = analyzer.get_detailed_report()
#print(report)
#summary_dict = analyzer.get_commit_summary_dict()
#print(summary_dict)
#time_difference_days = analyzer.get_time_between_commits_days()
#print(f"Time between commits: {time_difference_days} days")
#is_merge = analyzer.is_merge_commit()
#print(f"Is merge commit: {is_merge}")